### ISSUE TITLE
Config.py/get_source_config within Viadot2 possible bug

### ISSUE THREAD

**Issue by fdelgadodyvenia** [dyvenia/viadot#670] opened 2023-04-18 10:48 UTC
Function get_source_config () does not return info from yaml with the current implementaiton.
     return source_configs[source_configs.index(source_config)][key] OBS!!!!!!!!!!!!!
With this change, the function works properly:       
     return source_configs[source_configs.index(source_config)]

**Comment by trymzet** [comment] 2024-09-30 14:04
Hm this is old, I assume it was fixed in the mean time or a user error, since the unit test for this function is passing, and we don't have a reproducible example. Anyway, I simplified the func in #1070 so it should be easier to examine the logic.

**Closed by trymzet** 2024-09-30 14:04 UTC
Labels: bug
